FROM node:lts as builder

# use production environment
ENV NODE_ENV=production

WORKDIR /app

# install packages
COPY package*.json ./
RUN npm install

# copy source files
COPY . .

# build react app
RUN npm run build

FROM nginx

# copy nginx configuration
COPY ./proxy/default.conf.template /etc/nginx/templates/default.conf.template

# copy build files
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 8080

# start nginx
CMD ["nginx", "-g", "daemon off;"]
