FROM node:lts

# use production environment
ENV NODE_ENV=production

WORKDIR /api

# install packages
COPY package*.json ./
RUN npm install

# copy source files
COPY . .

EXPOSE 8080

# start node
CMD ["npm", "start"]
