FROM node:lts

# use development environment
ENV NODE_ENV=development

WORKDIR /api

# install packages
COPY package*.json ./
RUN npm install

# copy source files
COPY . .

EXPOSE 3000

# start nodemon
CMD ["npm", "run", "dev"]
